package form;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import koneksi.KoneksiDB;
import javax.swing.ButtonGroup;
import javax.swing.JSpinner;
import java.util.Date;

public class FormDataSiswa extends javax.swing.JFrame {

    private Connection conn = new KoneksiDB().koneksi();
    private DefaultTableModel tabmode;
    private ButtonGroup buttonGroup1;

    /**
     * Creates new form FormDataSiswa
     */
    public FormDataSiswa() {
        initComponents();
        kosong();
        aktif();
        datatable();
    }

    protected void aktif() {
        txtnama.requestFocus();
        tgl_lahir.setEditor(new JSpinner.DateEditor(tgl_lahir, "yyyy/MM/dd"));
    }

    protected void kosong() {
        txtid.setText("");
        txtnama.setText("");
        txtnisn.setText("");
        txtnik.setText("");
        txtkk.setText("");
        txtnamaayah.setText("");
        txtnikayah.setText("");
        txtnamaibu.setText("");
        txtnikibu.setText("");
        txtalamat.setText("");
        buttonGroup2.clearSelection();
        tgl_lahir.setValue(new Date());
    }

    protected void datatable() {
        Object[] Baris = {"ID", "Nama Siswa", "NISN", "NIK", "KK", "Tanggal Lahir", "Jenis Kelamin", "Nama Ayah", "NIK Ayah", "Nama Ibu", "NIK Ibu", "Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();

        try {
            String sql = "Select * FROM data_siswa where id like '%" + cariitem + "%' or Nama like '%" + cariitem + "%' order by id asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getDate(6),
                    hasil.getString(7),
                    hasil.getString(8),
                    hasil.getString(9),
                    hasil.getString(10),
                    hasil.getString(11),
                    hasil.getString(12)
                });
            }
            tblsiswa.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        txtnama = new javax.swing.JTextField();
        txtnik = new javax.swing.JTextField();
        txtnisn = new javax.swing.JTextField();
        txtnamaayah = new javax.swing.JTextField();
        txtnikayah = new javax.swing.JTextField();
        txtkk = new javax.swing.JTextField();
        txtnikibu = new javax.swing.JTextField();
        txtnamaibu = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsiswa = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bbatal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        rlaki = new javax.swing.JRadioButton();
        rperempuan = new javax.swing.JRadioButton();
        tgl_lahir = new javax.swing.JSpinner();
        btnExportCsv = new javax.swing.JButton();
        btnExportPdf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnikActionPerformed(evt);
            }
        });

        txtnisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnisnActionPerformed(evt);
            }
        });

        txtnamaayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaayahActionPerformed(evt);
            }
        });

        txtnikayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnikayahActionPerformed(evt);
            }
        });

        txtkk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkkActionPerformed(evt);
            }
        });

        txtnikibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnikibuActionPerformed(evt);
            }
        });

        txtnamaibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaibuActionPerformed(evt);
            }
        });

        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel1.setText("FORM DATA SISWA ");

        bsimpan.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        bsimpan.setText("SIMPAN ");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Nama Siswa");

        bubah.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        bubah.setText("UBAH ");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        bhapus.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bkeluar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        bkeluar.setText("KELUAR");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Siswa", "NISN", "NIK", "KK", "Tempat Tanggal Lahir ", "Nama Ayah ", "NIK Ayah ", "Nama Ibu ", "NIK Ibu ", "Alamat "
            }
        ));
        tblsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsiswa);

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("NIK");

        jLabel13.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel13.setText("Tanggal Lahir");

        jLabel14.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel14.setText("Nama Ayah");

        jLabel15.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel15.setText("NISN");

        jLabel16.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel16.setText("Nama Ibu");

        jLabel17.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel17.setText("KK");

        jLabel18.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel18.setText("Alamat");

        jLabel19.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel19.setText("NIK Ayah");

        jLabel20.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel20.setText("NIK Ibu");

        bbatal.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        bbatal.setText("BATAL");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("ID");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel21.setText("Jenis Kelamin");

        buttonGroup2.add(rlaki);
        rlaki.setText("Laki-Laki");

        buttonGroup2.add(rperempuan);
        rperempuan.setText("Perempuan");

        tgl_lahir.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));

        btnExportCsv.setText("Export CSV");
        btnExportCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportCsvActionPerformed(evt);
            }
        });

        btnExportPdf.setText("Print PDF");
        btnExportPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3)
                        .addGap(128, 128, 128)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel21)
                        .addGap(59, 59, 59)
                        .addComponent(rlaki)
                        .addGap(35, 35, 35)
                        .addComponent(rperempuan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel15)
                        .addGap(113, 113, 113)
                        .addComponent(txtnisn, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel14)
                        .addGap(67, 67, 67)
                        .addComponent(txtnamaayah, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel19)
                        .addGap(86, 86, 86)
                        .addComponent(txtnikayah, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bsimpan)
                                .addGap(127, 127, 127)
                                .addComponent(bubah)
                                .addGap(126, 126, 126)
                                .addComponent(bhapus)
                                .addGap(137, 137, 137)
                                .addComponent(bbatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bkeluar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(78, 78, 78)
                                .addComponent(txtnamaibu, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel20)
                                .addGap(97, 97, 97)
                                .addComponent(txtnikibu, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tgl_lahir)
                            .addComponent(txtnik, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(129, 129, 129)
                                .addComponent(txtkk, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(99, 99, 99)
                                .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bcari)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportCsv)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportPdf))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(rlaki))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(rperempuan)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnisn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnik, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnikayah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamaayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnamaibu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnikibu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bubah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportCsv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnikActionPerformed

    private void txtnisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnisnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnisnActionPerformed

    private void txtnamaayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaayahActionPerformed

    private void txtnikayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnikayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnikayahActionPerformed

    private void txtkkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkkActionPerformed

    private void txtnikibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnikibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnikibuActionPerformed

    private void txtnamaibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaibuActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String jenis = null;
        if (rlaki.isSelected()) {
            jenis = "Laki-Laki";
        } else if (rperempuan.isSelected()) {
            jenis = "Perempuan";
        }
        String sql = "insert into data_siswa (Nama, NISN, NIK, no_kk, tgl_lahir, jk, Nama_Ayah, NIK_Ayah, Nama_Ibu, NIK_Ibu, Alamat) values (?,?,?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);

            java.util.Date utilDate = (java.util.Date) tgl_lahir.getValue();

            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

            stat.setString(1, txtnama.getText());
            stat.setString(2, txtnisn.getText());
            stat.setString(3, txtnik.getText());
            stat.setString(4, txtkk.getText());
            stat.setDate(5, sqlDate);
            stat.setString(6, jenis);
            stat.setString(7, txtnamaayah.getText());
            stat.setString(8, txtnikayah.getText());
            stat.setString(9, txtnamaibu.getText());
            stat.setString(10, txtnikibu.getText());
            stat.setString(11, txtalamat.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            txtid.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal disimpan" + e);
        }
        datatable();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        String jenis = null;
        if (rlaki.isSelected()) {
            jenis = "Laki-Laki";
        } else if (rperempuan.isSelected()) {
            jenis = "Perempuan";
        }
        try {
            String sql = "update data_siswa set Nama=?,NISN=?,NIK=?,no_kk=?,tgl_lahir=?,jk=?,Nama_Ayah=?,NIK_Ayah=?,Nama_Ibu=?,NIK_Ibu=?,Alamat=? where id='" + txtid.getText() + "'";
            PreparedStatement stat = conn.prepareStatement(sql);

            java.util.Date utilDate = (java.util.Date) tgl_lahir.getValue();

            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

            stat.setString(1, txtnama.getText());
            stat.setString(2, txtnisn.getText());
            stat.setString(3, txtnik.getText());
            stat.setString(4, txtkk.getText());
            stat.setDate(5, sqlDate);
            stat.setString(6, jenis);
            stat.setString(7, txtnamaayah.getText());
            stat.setString(8, txtnikayah.getText());
            stat.setString(9, txtnamaibu.getText());
            stat.setString(10, txtnikibu.getText());
            stat.setString(11, txtalamat.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            txtid.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah" + e);
        }
        datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql = "delete from data_siswa where id = '" + txtid.getText() + "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtid.requestFocus();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus" + e);
            }
            datatable();
        }    }//GEN-LAST:event_bhapusActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        dashboard Dashboard = new dashboard();
        Dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed

    }//GEN-LAST:event_txtcariActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void tblsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsiswaMouseClicked
        int bar = tblsiswa.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        Object fObj = tabmode.getValueAt(bar, 5);
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        String j = tabmode.getValueAt(bar, 9).toString();
        String k = tabmode.getValueAt(bar, 10).toString();
        String l = tabmode.getValueAt(bar, 11).toString();

        txtid.setText(a);
        txtnama.setText(b);
        txtnisn.setText(c);
        txtnik.setText(d);
        txtkk.setText(e);
        if (fObj instanceof java.sql.Date) {
            // Convert java.sql.Date back to java.util.Date for the spinner
            java.sql.Date sqlDate = (java.sql.Date) fObj;
            tgl_lahir.setValue(new java.util.Date(sqlDate.getTime()));
        } else if (fObj instanceof java.util.Date) {
            // If it's already a java.util.Date (less likely from DB but possible)
            tgl_lahir.setValue((java.util.Date) fObj);
        } else {
            // If it's null or some other type, reset spinner to current date
            tgl_lahir.setValue(new Date());
        }
        if ("Laki-Laki".equals(g)) {
            rlaki.setSelected(true);
        } else {
            rperempuan.setSelected(true);
        }
        txtnamaayah.setText(h);
        txtnikayah.setText(i);
        txtnamaibu.setText(j);
        txtnikibu.setText(k);
        txtalamat.setText(l);
    }//GEN-LAST:event_tblsiswaMouseClicked

    private String escapeCsv(String data) {
        if (data == null) {
            return "\"\""; // Represent null as an empty quoted string
        }
        // Escape double quotes by doubling them: " -> ""
        String escapedData = data.replace("\"", "\"\"");
        // If data contains comma, double quote, or newline, enclose in double quotes
        if (data.contains(",") || data.contains("\"") || data.contains("\n") || data.contains("\r")) {
            return "\"" + escapedData + "\"";
        }
        // Otherwise, return the (potentially quote-escaped) data as is
        return escapedData;
    }

    private void btnExportCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportCsvActionPerformed

        String defaultFolder = System.getProperty("user.home");
        String filePath = defaultFolder + File.separator + "data_siswa_export.csv";

        String cariitem = txtcari.getText(); // Get search term like in datatable()

        String[] headers = {"ID", "Nama Siswa", "NISN", "NIK", "KK", "Tanggal Lahir", "Jenis Kelamin", "Nama Ayah", "NIK Ayah", "Nama Ibu", "NIK Ibu", "Alamat"};

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            writer.write(String.join(",", headers));
            writer.newLine();

            String sql = "SELECT * FROM data_siswa WHERE id LIKE '%" + cariitem + "%' OR Nama LIKE '%" + cariitem + "%' ORDER BY id ASC";

            try (Statement stat = conn.createStatement(); ResultSet hasil = stat.executeQuery(sql)) {
                while (hasil.next()) {
                    List<String> rowData = new ArrayList<>();

                    rowData.add(escapeCsv(hasil.getString(1))); // ID
                    rowData.add(escapeCsv(hasil.getString(2))); // Nama Siswa
                    rowData.add(escapeCsv(hasil.getString(3))); // NISN
                    rowData.add(escapeCsv(hasil.getString(4))); // NIK
                    rowData.add(escapeCsv(hasil.getString(5))); // KK

                    java.sql.Date tglLahir = hasil.getDate(6); // Get date
                    rowData.add(escapeCsv(tglLahir == null ? "" : tglLahir.toString())); // Tanggal Lahir (handle null)

                    rowData.add(escapeCsv(hasil.getString(7))); // Jenis Kelamin
                    rowData.add(escapeCsv(hasil.getString(8))); // Nama Ayah
                    rowData.add(escapeCsv(hasil.getString(9))); // NIK Ayah
                    rowData.add(escapeCsv(hasil.getString(10))); // Nama Ibu
                    rowData.add(escapeCsv(hasil.getString(11))); // NIK Ibu
                    rowData.add(escapeCsv(hasil.getString(12))); // Alamat

                    // Join the escaped data with commas and write the row
                    writer.write(String.join(",", rowData));
                    writer.newLine();
                }

                JOptionPane.showMessageDialog(this, // Assuming 'this' refers to your JFrame/JPanel
                        "Data berhasil diekspor ke:\n" + filePath,
                        "Ekspor Berhasil",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,
                        "Gagal mengambil data dari database: " + e.getMessage(),
                        "Database Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace(); // Good for debugging

            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal menulis file CSV: " + e.getMessage(),
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnExportCsvActionPerformed

    private void btnExportPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPdfActionPerformed
        String defaultFolder = System.getProperty("user.home");
        String filePath = defaultFolder + File.separator + "data_siswa_lengkap.pdf";

        Document document = new Document(PageSize.A4.rotate()); // Use landscape for potentially wide table

        try {
            PdfWriter.getInstance(document, new FileOutputStream(filePath));

            document.open();

            Font titleFont = new Font(Font.HELVETICA, 18, Font.BOLD);
            Paragraph title = new Paragraph("Data Lengkap Siswa", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20); // Add some space after the title
            document.add(title);

            PdfPTable pdfTable = new PdfPTable(12);
            pdfTable.setWidthPercentage(100); // Make table width 100% of page width

            Font headerFont = new Font(Font.HELVETICA, 10, Font.BOLD, Color.WHITE);
            PdfPCell cell = new PdfPCell();
            cell.setBackgroundColor(Color.GRAY);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPadding(5);

            // Add table headers
            String[] headers = {"ID", "Nama Siswa", "NISN", "NIK", "KK", "Tgl Lahir", "JK", "Nama Ayah", "NIK Ayah", "Nama Ibu", "NIK Ibu", "Alamat"};
            for (String header : headers) {
                cell.setPhrase(new Phrase(header, headerFont));
                pdfTable.addCell(cell);
            }
            pdfTable.setHeaderRows(1); // Treat the first row as a header for repeating on new pages

            String sql = "SELECT * FROM data_siswa ORDER BY id ASC"; // Get ALL data

            try (Statement stat = conn.createStatement(); ResultSet hasil = stat.executeQuery(sql)) {
                // Define data cell font
                Font dataFont = new Font(Font.HELVETICA, 9);
                PdfPCell dataCell = new PdfPCell();
                dataCell.setPadding(4);
                dataCell.setVerticalAlignment(Element.ALIGN_MIDDLE);

                while (hasil.next()) {
                    dataCell.setPhrase(new Phrase(hasil.getString(1) == null ? "" : hasil.getString(1), dataFont)); // ID
                    pdfTable.addCell(dataCell);
                    dataCell.setPhrase(new Phrase(hasil.getString(2) == null ? "" : hasil.getString(2), dataFont)); // Nama Siswa
                    pdfTable.addCell(dataCell);
                    dataCell.setPhrase(new Phrase(hasil.getString(3) == null ? "" : hasil.getString(3), dataFont)); // NISN
                    pdfTable.addCell(dataCell);
                    dataCell.setPhrase(new Phrase(hasil.getString(4) == null ? "" : hasil.getString(4), dataFont)); // NIK
                    pdfTable.addCell(dataCell);
                    dataCell.setPhrase(new Phrase(hasil.getString(5) == null ? "" : hasil.getString(5), dataFont)); // KK
                    pdfTable.addCell(dataCell);
                    java.sql.Date tglLahir = hasil.getDate(6);
                    dataCell.setPhrase(new Phrase(tglLahir == null ? "" : tglLahir.toString(), dataFont)); // Tgl Lahir
                    pdfTable.addCell(dataCell);
                    dataCell.setPhrase(new Phrase(hasil.getString(7) == null ? "" : hasil.getString(7), dataFont)); // JK
                    pdfTable.addCell(dataCell);
                    dataCell.setPhrase(new Phrase(hasil.getString(8) == null ? "" : hasil.getString(8), dataFont)); // Nama Ayah
                    pdfTable.addCell(dataCell);
                    dataCell.setPhrase(new Phrase(hasil.getString(9) == null ? "" : hasil.getString(9), dataFont)); // NIK Ayah
                    pdfTable.addCell(dataCell);
                    dataCell.setPhrase(new Phrase(hasil.getString(10) == null ? "" : hasil.getString(10), dataFont)); // Nama Ibu
                    pdfTable.addCell(dataCell);
                    dataCell.setPhrase(new Phrase(hasil.getString(11) == null ? "" : hasil.getString(11), dataFont)); // NIK Ibu
                    pdfTable.addCell(dataCell);
                    dataCell.setPhrase(new Phrase(hasil.getString(12) == null ? "" : hasil.getString(12), dataFont)); // Alamat
                    pdfTable.addCell(dataCell);
                }
            } catch (SQLException e) { // Catch Database errors
                JOptionPane.showMessageDialog(this,
                        "Gagal mengambil data dari database: " + e.getMessage(),
                        "Database Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }

            document.add(pdfTable);

            JOptionPane.showMessageDialog(this, // Assuming 'this' is your component
                    "Data lengkap berhasil diekspor ke PDF:\n" + filePath,
                    "Ekspor PDF Berhasil",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (DocumentException | FileNotFoundException e) { // Catch PDF specific errors
            JOptionPane.showMessageDialog(this,
                    "Gagal membuat file PDF: " + e.getMessage(),
                    "PDF Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            // ALWAYS close the document in a finally block
            // This is crucial to ensure the PDF file is finalized and saved correctly.
            if (document != null && document.isOpen()) {
                document.close();
            }
        }
    }//GEN-LAST:event_btnExportPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDataSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btnExportCsv;
    private javax.swing.JButton btnExportPdf;
    private javax.swing.JButton bubah;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rlaki;
    private javax.swing.JRadioButton rperempuan;
    private javax.swing.JTable tblsiswa;
    private javax.swing.JSpinner tgl_lahir;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkk;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnamaayah;
    private javax.swing.JTextField txtnamaibu;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtnikayah;
    private javax.swing.JTextField txtnikibu;
    private javax.swing.JTextField txtnisn;
    // End of variables declaration//GEN-END:variables
}
