package form;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Types;
import java.awt.event.KeyEvent;
import database.Database; // Changed import
import java.util.Date;

public class Siswa extends javax.swing.JFrame {

    private Connection conn; // Modified: Initialize in constructor
    private DefaultTableModel tabmode;
    private String selectedSiswaId;
    // private ButtonGroup buttonGroup1; // buttonGroup2 is used by NetBeans designer

    /**
     * Creates new form FormDataSiswa
     */
    public Siswa() {
        initComponents();
        lblSelectedSiswa.setText("-"); // Initialize label
        selectedSiswaId = null;      // Initialize ID
        try {
            conn = Database.getConnection(); // Added: Get connection from Database class
            reset();
            loadTable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to connect to database: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            // Optionally, disable UI components or close the form
        }
    }

    private void reset() {
        // txtid.setText(""); // No txtid field
        txtNama.setText("");
        txtNisn.setText("");
        txtNis.setText("");
        txtNoKk.setText("");
        txtNamaAyah.setText("");
        txtNikAyah.setText("");
        txtNamaIbu.setText("");
        txtNikIbu.setText("");
        txtAlamat.setText("");
        buttonGroup2.clearSelection(); // Assuming rlaki and rperempuan are in buttonGroup2
        spnTanggalLahir.setValue(new Date());
        lblSelectedSiswa.setText("-"); // Reset selected siswa label
        selectedSiswaId = null;      // Clear selected siswa ID
    }

    private void loadTable() {
        Object[] Baris = {"ID", "Nama Siswa", "NISN", "NIS", "KK", "Tanggal Lahir", "Jenis Kelamin", "Nama Ayah", "NIK Ayah", "Nama Ibu", "NIK Ibu", "Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtSearch.getText();

        try {
            String sql = "SELECT id, nama, nisn, nis, no_kk, tanggal_lahir, jenis_kelamin, nama_ayah, nik_ayah, nama_ibu, nik_ibu, alamat FROM siswa WHERE id LIKE ? OR nama LIKE ? ORDER BY id ASC";
            PreparedStatement stat = conn.prepareStatement(sql);
            String searchTerm = "%" + cariitem + "%";
            stat.setString(1, searchTerm);
            stat.setString(2, searchTerm);
            ResultSet hasil = stat.executeQuery();

            while (hasil.next()) {
                Boolean jkBool = hasil.getObject("jenis_kelamin") != null ? hasil.getBoolean("jenis_kelamin") : null;
                String jenisKelaminStr = "";
                if (jkBool != null) {
                    jenisKelaminStr = jkBool ? "Laki-laki" : "Perempuan";
                }

                tabmode.addRow(new Object[]{
                    hasil.getString("id"),
                    hasil.getString("nama"),
                    hasil.getString("nisn"),
                    hasil.getString("nis"), // Changed from NIK
                    hasil.getString("no_kk"),
                    hasil.getDate("tanggal_lahir"),
                    jenisKelaminStr,
                    hasil.getString("nama_ayah"),
                    hasil.getString("nik_ayah"),
                    hasil.getString("nama_ibu"),
                    hasil.getString("nik_ibu"),
                    hasil.getString("alamat")
                });
            }
            tblSiswa.setModel(tabmode);
        } catch (SQLException e) { // Catch SQLException specifically
            JOptionPane.showMessageDialog(this, "Data siswa gagal dipanggil: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void resetUI() {
        loadTable();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        txtNama = new javax.swing.JTextField();
        txtNis = new javax.swing.JTextField();
        txtNisn = new javax.swing.JTextField();
        txtNamaAyah = new javax.swing.JTextField();
        txtNikAyah = new javax.swing.JTextField();
        txtNoKk = new javax.swing.JTextField();
        txtNikIbu = new javax.swing.JTextField();
        txtNamaIbu = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSiswa = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        rlaki = new javax.swing.JRadioButton();
        rperempuan = new javax.swing.JRadioButton();
        spnTanggalLahir = new javax.swing.JSpinner();
        lblSelectedSiswa = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 127, 244, 33));
        getContentPane().add(txtNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 178, 242, 33));
        getContentPane().add(txtNisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 127, 244, 33));
        getContentPane().add(txtNamaAyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 281, 244, 33));
        getContentPane().add(txtNikAyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 281, 244, 33));
        getContentPane().add(txtNoKk, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 178, 244, 33));
        getContentPane().add(txtNikIbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 244, 33));
        getContentPane().add(txtNamaIbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 336, 244, 33));
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 244, 33));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel1.setText("FORM DATA SISWA ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 6, -1, 49));

        btnCreate.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnCreate.setText("SIMPAN ");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 402, -1, 33));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Nama Siswa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 131, -1, 26));

        btnUpdate.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnUpdate.setText("UBAH ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 402, -1, 33));

        btnDelete.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnDelete.setText("HAPUS");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 402, -1, 33));

        btnExit.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnExit.setText("KELUAR");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 402, -1, 33));

        tblSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Siswa", "NISN", "NIK", "KK", "Tempat Tanggal Lahir ", "Nama Ayah ", "NIK Ayah ", "Nama Ibu ", "NIK Ibu ", "Alamat "
            }
        ));
        tblSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSiswa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 517, 990, 293));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 467, 223, 30));

        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 466, -1, 33));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("NIS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 182, -1, 26));

        jLabel13.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel13.setText("Tanggal Lahir");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 230, -1, 26));

        jLabel14.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel14.setText("Nama Ayah");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 284, -1, 26));

        jLabel15.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel15.setText("NISN");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, 26));

        jLabel16.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel16.setText("Nama Ibu");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 339, -1, 26));

        jLabel17.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel17.setText("KK");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, 26));

        jLabel18.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel18.setText("Alamat");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, 26));

        jLabel19.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel19.setText("NIK Ayah");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, 26));

        jLabel20.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel20.setText("NIK Ibu");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, 26));

        btnReset.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnReset.setText("BATAL");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 402, -1, 33));

        jLabel21.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel21.setText("Jenis Kelamin");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, 26));

        buttonGroup2.add(rlaki);
        rlaki.setText("Laki-Laki");
        getContentPane().add(rlaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        buttonGroup2.add(rperempuan);
        rperempuan.setText("Perempuan");
        getContentPane().add(rperempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, -1, -1));

        spnTanggalLahir.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        getContentPane().add(spnTanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 229, 244, 33));

        lblSelectedSiswa.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lblSelectedSiswa.setText("[PLACEHOLDER]");
        getContentPane().add(lblSelectedSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 76, -1, 26));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("Siswa dipilih:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 76, -1, 26));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String nama = txtNama.getText();
        String nisn = txtNisn.getText();
        String nis = txtNis.getText();
        String noKk = txtNoKk.getText();
        java.util.Date utilTanggalLahir = (java.util.Date) spnTanggalLahir.getValue();
        String namaAyah = txtNamaAyah.getText();
        String nikAyah = txtNikAyah.getText();
        String namaIbu = txtNamaIbu.getText();
        String nikIbu = txtNikIbu.getText();
        String alamat = txtAlamat.getText();

        if (nama.isEmpty() || nisn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Siswa dan NISN tidak boleh kosong.", "Validasi Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.sql.Date sqlTanggalLahir = null;
        if (utilTanggalLahir != null) {
            sqlTanggalLahir = new java.sql.Date(utilTanggalLahir.getTime());
        }

        Boolean jenisKelaminDbValue = null;
        if (rlaki.isSelected()) {
            jenisKelaminDbValue = true; // 1 for Laki-laki
        } else if (rperempuan.isSelected()) {
            jenisKelaminDbValue = false; // 0 for Perempuan
        }

        String sql = "INSERT INTO siswa (nama, nisn, nis, no_kk, tanggal_lahir, jenis_kelamin, nama_ayah, nik_ayah, nama_ibu, nik_ibu, alamat) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, nama);
            stat.setString(2, nisn);
            setStringOrNull(stat, 3, nis);
            setStringOrNull(stat, 4, noKk);
            setDateOrNull(stat, 5, sqlTanggalLahir);
            setBooleanOrNull(stat, 6, jenisKelaminDbValue);
            setStringOrNull(stat, 7, namaAyah);
            setStringOrNull(stat, 8, nikAyah);
            setStringOrNull(stat, 9, namaIbu);
            setStringOrNull(stat, 10, nikIbu);
            setStringOrNull(stat, 11, alamat);

            int rowsInserted = stat.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Data Siswa berhasil ditambahkan!");
                resetUI();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data siswa: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedSiswaId == null || selectedSiswaId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih siswa yang akan diupdate.", "Siswa Belum Dipilih", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nama = txtNama.getText();
        String nisn = txtNisn.getText();
        String nis = txtNis.getText();
        String noKk = txtNoKk.getText();
        java.util.Date utilTanggalLahir = (java.util.Date) spnTanggalLahir.getValue();
        String namaAyah = txtNamaAyah.getText();
        String nikAyah = txtNikAyah.getText();
        String namaIbu = txtNamaIbu.getText();
        String nikIbu = txtNikIbu.getText();
        String alamat = txtAlamat.getText();

        if (nama.isEmpty() || nisn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Siswa dan NISN tidak boleh kosong.", "Validasi Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.sql.Date sqlTanggalLahir = null;
        if (utilTanggalLahir != null) {
            sqlTanggalLahir = new java.sql.Date(utilTanggalLahir.getTime());
        }

        Boolean jenisKelaminDbValue = null;
        if (rlaki.isSelected()) {
            jenisKelaminDbValue = true; // 1 for Laki-laki
        } else if (rperempuan.isSelected()) {
            jenisKelaminDbValue = false; // 0 for Perempuan
        }

        String sql = "UPDATE siswa SET nama=?, nisn=?, nis=?, no_kk=?, tanggal_lahir=?, jenis_kelamin=?, nama_ayah=?, nik_ayah=?, nama_ibu=?, nik_ibu=?, alamat=? WHERE id=?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, nama);
            stat.setString(2, nisn);
            setStringOrNull(stat, 3, nis);
            setStringOrNull(stat, 4, noKk);
            setDateOrNull(stat, 5, sqlTanggalLahir);
            setBooleanOrNull(stat, 6, jenisKelaminDbValue);
            setStringOrNull(stat, 7, namaAyah);
            setStringOrNull(stat, 8, nikAyah);
            setStringOrNull(stat, 9, namaIbu);
            setStringOrNull(stat, 10, nikIbu);
            setStringOrNull(stat, 11, alamat);
            stat.setString(12, selectedSiswaId);

            int rowsUpdated = stat.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Data Siswa berhasil diupdate!");
                resetUI();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengupdate data siswa. Siswa tidak ditemukan atau data tidak berubah.", "Update Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengupdate data siswa: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedSiswaId == null || selectedSiswaId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih siswa yang akan dihapus.", "Siswa Belum Dipilih", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus siswa: " + lblSelectedSiswa.getText() + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String sql = "DELETE FROM siswa WHERE id = ?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, selectedSiswaId);

            int rowsDeleted = stat.executeUpdate();
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Data Siswa berhasil dihapus!");
                resetUI();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data siswa. Siswa tidak ditemukan.", "Hapus Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data siswa: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    // Helper methods for PreparedStatement
    private void setStringOrNull(PreparedStatement ps, int index, String value) throws SQLException {
        if (value == null || value.trim().isEmpty()) {
            ps.setNull(index, Types.VARCHAR);
        } else {
            ps.setString(index, value);
        }
    }

    private void setDateOrNull(PreparedStatement ps, int index, java.sql.Date value) throws SQLException {
        if (value == null) {
            ps.setNull(index, Types.DATE);
        } else {
            ps.setDate(index, value);
        }
    }

    private void setBooleanOrNull(PreparedStatement ps, int index, Boolean value) throws SQLException {
        if (value == null) {
            ps.setNull(index, Types.BOOLEAN);
        } else {
            ps.setBoolean(index, value);
        }
    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dashboard Dashboard = new dashboard();
        Dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        loadTable();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loadTable();
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetUI();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSiswaMouseClicked
        int baris = tblSiswa.getSelectedRow();
        if (baris != -1) {
            selectedSiswaId = tblSiswa.getValueAt(baris, 0).toString();
            String nama = tblSiswa.getValueAt(baris, 1).toString(); // Nama is NOT NULL
            lblSelectedSiswa.setText(nama); // Update label

            txtNama.setText(nama);
            txtNisn.setText(tblSiswa.getValueAt(baris, 2) != null ? tblSiswa.getValueAt(baris, 2).toString() : ""); // NISN is NOT NULL
            txtNis.setText(tblSiswa.getValueAt(baris, 3) != null ? tblSiswa.getValueAt(baris, 3).toString() : "");
            txtNoKk.setText(tblSiswa.getValueAt(baris, 4) != null ? tblSiswa.getValueAt(baris, 4).toString() : "");

            Object tanggalLahirObj = tblSiswa.getValueAt(baris, 5);
            if (tanggalLahirObj instanceof java.util.Date) { // Covers java.sql.Date
                spnTanggalLahir.setValue(new java.util.Date(((java.util.Date) tanggalLahirObj).getTime()));
            } else {
                spnTanggalLahir.setValue(new Date()); // Default if null or other type
            }

            String jenisKelaminStr = tblSiswa.getValueAt(baris, 6) != null ? tblSiswa.getValueAt(baris, 6).toString() : "";
            if ("Laki-laki".equalsIgnoreCase(jenisKelaminStr)) {
                rlaki.setSelected(true);
            } else if ("Perempuan".equalsIgnoreCase(jenisKelaminStr)) {
                rperempuan.setSelected(true);
            } else {
                buttonGroup2.clearSelection(); // Clear if no match or null
            }

            txtNamaAyah.setText(tblSiswa.getValueAt(baris, 7) != null ? tblSiswa.getValueAt(baris, 7).toString() : "");
            txtNikAyah.setText(tblSiswa.getValueAt(baris, 8) != null ? tblSiswa.getValueAt(baris, 8).toString() : "");
            txtNamaIbu.setText(tblSiswa.getValueAt(baris, 9) != null ? tblSiswa.getValueAt(baris, 9).toString() : "");
            txtNikIbu.setText(tblSiswa.getValueAt(baris, 10) != null ? tblSiswa.getValueAt(baris, 10).toString() : "");
            txtAlamat.setText(tblSiswa.getValueAt(baris, 11) != null ? tblSiswa.getValueAt(baris, 11).toString() : "");
        }
    }//GEN-LAST:event_tblSiswaMouseClicked

    // Removed unused escapeCsv method
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelectedSiswa;
    private javax.swing.JRadioButton rlaki;
    private javax.swing.JRadioButton rperempuan;
    private javax.swing.JSpinner spnTanggalLahir;
    private javax.swing.JTable tblSiswa;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaAyah;
    private javax.swing.JTextField txtNamaIbu;
    private javax.swing.JTextField txtNikAyah;
    private javax.swing.JTextField txtNikIbu;
    private javax.swing.JTextField txtNis;
    private javax.swing.JTextField txtNisn;
    private javax.swing.JTextField txtNoKk;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
